version: '3'

services:
    server:
        depends_on:
            - db
        environment:
          REACT_APP_API_SERVER: https://api.pro-man.co
          REACT_APP_PUBLIC_HOSTNAME: https://api.pro-man.co
          EMAIL_LOGIN: pro-man2217@outlook.com
          EMAIL_PASSWORD: TeckyCanada2222
        image: cmyip6/pro-man:latest
        ports:
            - "8080:8080"
    db: 
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data